apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story-app
          image: vadozy/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        # - name: story-volume
        #   emptyDir: {}
        # - name: story-volume
        #   hostPath:
        #     path: /data
        #     type: DirectoryOrCreate
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pv-claim
