apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pv-claim
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 90Mi
