apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story
  ports:
    - appProtocol: "TCP"
      port: 80 # outside port
      targetPort: 3000 # port insode container
  type: LoadBalancer
