version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - "8000:3000"
    env_file:
      - ./env/auth.env
  users:
    build: ./users-api
    ports:
      - "8080:3000"
    env_file:
      - ./env/users.env
