apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - appProtocol: "TCP"
      port: 80 # outside port
      targetPort: 80 # port inside container
  type: ClusterIP
