apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - appProtocol: "TCP"
      port: 80 # outside port
      targetPort: 80 # port inside container
  type: LoadBalancer
