apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: vadozy/kub-demo-tasks-api:latest
          env:
            - name: AUTH_HOSTNAME
              value: auth-service
            - name: TASKS_FOLDER
              value: tasks
