apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - appProtocol: "TCP"
      port: 8080 # outside port
      targetPort: 8080 # port inside container
  type: LoadBalancer
