apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: vadozy/kub-demo-users-api:latest
          env:
            - name: AUTH_HOSTNAME
              value: auth-service
