apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
    # tier: backend
  ports:
    - appProtocol: "TCP"
      port: 80 # outside port
      targetPort: 8080 # port insode container
  type: LoadBalancer
