FROM node:14-alpine3.13 as my_react_build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# Multistage build example !!

FROM nginx:1.19.10-alpine

COPY --from=my_react_build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]